# Generated by Django 3.1.4 on 2022-02-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personincompany',
            old_name='person',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='personincompany',
            name='phone_number',
            field=models.SmallIntegerField(max_length=10, unique=True),
        ),
    ]
